### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by dennisguse** [khertan/ForRunners#47]
Sadly, the instructions on how to build ForRunners are not documented.
Thus, new developers (as me) will need to spend some time on figuring out how to setup the build toolchain.

It would be great to
a) describe all used tools (or give links to a proper description), 
b) give install instructions for all tools (at least for one OS), and
c) provide all commands to completely build the project.

**Comment by dratasich** [comment]
First, congrats to this nice app! I wanted to try out your fixes and build it for my phone. (I'm new to cordova and it has been a long time since I programmed apps with the AndroidStudio.)

I tried your BUILD instructions with the docker image [bitriseio/docker-android](https://hub.docker.com/r/bitriseio/docker-android/) (quite big, but well maintained with latest sdk and tools) instead of installing cordova by hand ;).

- ``sdkmanager --list``, build-tools: 27.0.0, platform-tools 27.0.1, tools: 25.2.5
- ionic 3.20.0
- cordova 8.0.0
- ``cordova platform ls``
```
Installed platforms:
  android 6.3.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```

First problem I ran into: location of the ``AndroidManifest.xml``. ``ionic cordova run android`` searches in ``platforms/android/``. I made a symlink (``platforms/android/AndroidManifest.xml`` to ``platforms/android/CordovaLib/AndroidManifest.xml``) and plugins started to get installed.

However, other problems arise (version errors, fetch failed). However, the show-stopper was:
```
(node:3348) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/tmp/platforms/android/res/values/strings.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (/tmp/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
    at updateProjectAccordingTo (/tmp/platforms/android/cordova/lib/prepare.js:171:30)
    at /tmp/platforms/android/cordova/lib/prepare.js:47:16
    at _fulfilled (/tmp/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/tmp/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/tmp/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /tmp/platforms/android/cordova/node_modules/q/q.js:570:49
    at runSingle (/tmp/platforms/android/cordova/node_modules/q/q.js:137:13)
(node:3348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ERROR] An error occurred while running cordova run android (exit code 1).
```

I don't know if this is just because I have a different version of ionic or cordova (see a [discussion in the ionic repo](https://github.com/ionic-team/ionic/issues/13702)). What versions do you use? 

Best,
Denise

**Comment by dratasich** [comment]
I got the build to work and updated the BUILD file: #70.
But only when I removed the platforms folder first.

I think the platforms folder can and [should](https://cordova.apache.org/docs/en/latest/reference/cordova-cli/index.html#version-control) be removed from the repository completely.

Best,
Denise

**Comment by brvier** [comment]
Unfortunately it s a necessary for Fdroid building. But I agree platform should not be in repository.

Benoît HERVIER - http://rvier.fr
