### ISSUE TITLE
ForRunners-1.2.1beta1 crashes on start

### ISSUE THREAD

**Issue by akamaus** [khertan/ForRunners#71]
After upgrading from 1.1.3 version (I had to delete previously installed version I got from fdroid, btw, because installer complained about different keys) app crashes instant after it starts. I test this on Xiaomi mi4c (android 5.1) 

Adb logcat shows these lines:

> V/WindowManager( 1037): Adding window Window{27ca8ad9 u0 net.khertan.forrunners/net.khertan.forrunners.MainActivity} at 20 of 29 (before Window{273e29d8 u0 Starting net.khertan.forrunners})
> W/WhitelistPlugin( 3939): Found <access launch-external> within config.xml. Please use <allow-intent> instead.
> D/CordovaWebViewImpl( 3939): >>> loadUrl(file:///android_asset/www/index.html)
> 
> D/CordovaActivity( 3939): Started the activity.
> D/CordovaActivity( 3939): Resumed the activity.
> V/WindowManager( 1037): Adding window Window{cc7937f u0 net.khertan.forrunners/net.khertan.forrunners.MainActivity} at 20 of 30 (before Window{27ca8ad9 u0 net.khertan.forrunners/net.khertan.forrunners.MainActivity})
> W/chromium( 3939): [WARNING:data_reduction_proxy_config.cc(630)] SPDY proxy OFF at startup
> 
> I/OpenGLRenderer( 3939): Initialized EGL, version 1.4
> D/OpenGLRenderer( 3939): Enabling debug mode 0
> I/Timeline( 1037): Timeline: App_transition_stopped time:3555724
> 
> I/ActivityManager( 1037): Displayed net.khertan.forrunners/.MainActivity: +485ms
> I/Timeline( 1037): Timeline: Activity_windows_visible id: ActivityRecord{6f4bc43 u0 net.khertan.forrunners/.MainActivity t11755} time:3555775
> D/CordovaWebViewImpl( 3939): onPageDidNavigate(file:///android_asset/www/index.html)
> I/Timeline( 3939): Timeline: Activity_idle id: android.os.BinderProxy@38f95a37 time:3555776
> W/cr.BindingManager( 3939): Cannot call determinedVisibility() - never saw a connection for the pid: 3939
> D/SystemWebChromeClient( 3939): file:///android_asset/www/index.html: Line 5 : The key "viewport-fit" is not recognized and ignored.
> I/chromium( 3939): [INFO:CONSOLE(5)] "The key "viewport-fit" is not recognized and ignored.", source: file:///android_asset/www/index.html (5)
> D/JsMessageQueue( 3939): Set native->JS mode to EvalBridgeMode
> I/TextToSpeech( 3939): Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
> V/LocationPolicy( 1037): onProcessStateChanged
> I/TextToSpeech( 3939): Sucessfully bound to com.svox.pico
> V/ProcessObserver( 5190): onProcessStateChanged
> I/TextToSpeech( 3939): Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
> D/AndroidRuntime( 3939): Shutting down VM
> E/AndroidRuntime( 3939): FATAL EXCEPTION: main
> E/AndroidRuntime( 3939): Process: net.khertan.forrunners, PID: 3939
> E/AndroidRuntime( 3939): java.lang.NullPointerException: collection == null
> E/AndroidRuntime( 3939):        at android.os.Parcel.readException(Parcel.java:1552)
> E/AndroidRuntime( 3939):        at android.os.Parcel.readException(Parcel.java:1499)
> E/AndroidRuntime( 3939):        at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:700)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1589)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1586)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2232)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:742)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:732)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech.getVoices(TextToSpeech.java:1586)
> E/AndroidRuntime( 3939):        at org.apache.cordova.speech.SpeechSynthesis.getVoices(SpeechSynthesis.java:172)
> E/AndroidRuntime( 3939):        at org.apache.cordova.speech.SpeechSynthesis.onInit(SpeechSynthesis.java:258)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech.access$1400(TextToSpeech.java:59)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2146)
> E/AndroidRuntime( 3939):        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2101)
> E/AndroidRuntime( 3939):        at android.os.AsyncTask.finish(AsyncTask.java:636)
> E/AndroidRuntime( 3939):        at android.os.AsyncTask.access$500(AsyncTask.java:177)
> E/AndroidRuntime( 3939):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
> E/AndroidRuntime( 3939):        at android.os.Handler.dispatchMessage(Handler.java:102)
> E/AndroidRuntime( 3939):        at android.os.Looper.loop(Looper.java:135)
> E/AndroidRuntime( 3939):        at android.app.ActivityThread.main(ActivityThread.java:5275)
> E/AndroidRuntime( 3939):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime( 3939):        at java.lang.reflect.Method.invoke(Method.java:372)
> E/AndroidRuntime( 3939):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:910)
> E/AndroidRuntime( 3939):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:705)
> I/WhetstoneService( 4671): Receive am_crash event for pid: 3939
> W/KloServer( 4671): Aborted broadcast does not supprt for: net.khertan.forrunners
> W/ActivityManager( 1037):   Force finishing activity 1 net.khertan.forrunners/.MainActivity
> I/octvm_klo( 6541): [am_crash][1522501680]:[3939,0,net.khertan.forrunners,13155908,java.lang.NullPointerException,collection == null,Parcel.java,1552]

**Comment by brvier** [comment]
So it s look like there is a problem getting the speech synthetiser voice : android.speech.tts.TextToSpeech.getVoices

You are the third user reporting me with a Xiaomi device

**Comment by natrius** [comment]
1.2.2beta1 - "App could not be installed".
OnePlus3, LineageOS 15.1, Android 8.1

```
[04-20 11:16:53.460 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:53.460 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:53.919 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:53.920 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:53.921 32393:32393 W/Notification]
Use of stream types is deprecated for operations other than volume control

[04-20 11:16:53.921 32393:32393 W/Notification]
See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case

[04-20 11:16:53.929 32393:32393 I/zygote64]
Deoptimizing android.graphics.Typeface android.support.v7.widget.TintTypedArray.getFont(int, int, android.support.v4.content.res.ResourcesCompat$FontCallback) due to JIT inline cache

[04-20 11:16:54.012 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:54.012 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:54.202 2272:2297 I/zygote64]
Background concurrent copying GC freed 55407(2MB) AllocSpace objects, 7(332KB) LOS objects, 44% free, 15MB/27MB, paused 365us total 262.620ms

[04-20 11:16:54.470 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:54.681 2272:3331 I/ActivityManager]
START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10032

[04-20 11:16:54.470 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:54.694 3080:3080 E/BufferItemConsumer]
[unnamed-3080-132] Failed to release buffer: Unknown error -1 (1)

[04-20 11:16:54.699 5585:15345 W/WebSocketConnection]
Sending keep alive...

[04-20 11:16:54.704 32393:32393 D/MyDeviceLogs]
[Logcat] onActivityInBackground

[04-20 11:16:54.768 2272:2358 E/NotificationService]
Suppressing notification from package by user request.

[04-20 11:16:54.769 2272:2389 D/AutofillManagerService]
Close system dialogs

[04-20 11:16:54.812 3080:3080 E/BufferItemConsumer]
[unnamed-3080-133] Failed to release buffer: Unknown error -1 (1)

[04-20 11:16:54.906 5585:15209 W/WebSocketConnection]
WSC onMessage()

[04-20 11:16:54.906 5585:15209 W/WebSocketConnection]
Message Type: 2

[04-20 11:16:55.048 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:55.049 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:55.175 3080:3103 I/zygote64]
NativeAlloc concurrent copying GC freed 199871(8MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 14MB/29MB, paused 175us total 238.530ms

[04-20 11:16:55.267 2272:5457 I/OpenGLRenderer]
Initialized EGL, version 1.4

[04-20 11:16:55.267 2272:5457 D/OpenGLRenderer]
Swap behavior 2

[04-20 11:16:55.483 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:55.999 3080:3080 I/chatty]
uid=10032(com.android.systemui) identical 2 lines

[04-20 11:16:56.000 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:56.223 3080:3103 I/zygote64]
NativeAlloc concurrent copying GC freed 14417(754KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 14MB/29MB, paused 427us total 172.609ms

[04-20 11:16:56.515 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:56.515 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:56.848 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:56.848 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:56.871 3080:3080 E/BufferItemConsumer]
[unnamed-3080-134] Failed to release buffer: Unknown error -1 (1)

[04-20 11:16:57.021 3080:3080 E/BufferItemConsumer]
[unnamed-3080-135] Failed to release buffer: Unknown error -1 (1)

[04-20 11:16:57.162 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:57.163 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:57.375 3080:3103 I/zygote64]
NativeAlloc concurrent copying GC freed 29746(1218KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 14MB/28MB, paused 416us total 204.418ms

[04-20 11:16:57.519 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:57.519 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:57.612 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:57.616 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:57.661 548:548 D/SurfaceFlinger]
duplicate layer name: changing com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity to com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity#1

[04-20 11:16:57.816 3080:11493 I/zygote64]
Explicit concurrent copying GC freed 11805(544KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/27MB, paused 200us total 436.982ms

[04-20 11:16:57.957 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:57.958 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:58.418 5707:5707 I/trackworktime]
executing periodic hook

[04-20 11:16:58.419 5707:5707 I/trackworktime]
checking location-based tracking

[04-20 11:16:58.421 5707:5707 I/trackworktime]
location-based tracking service stopped

[04-20 11:16:58.421 5707:5707 I/trackworktime]
checking wifi-based tracking

[04-20 11:16:58.422 5707:5707 I/trackworktime]
wifi-based tracking service stopped

[04-20 11:16:58.422 5707:5707 I/trackworktime]
checking persistent notification

[04-20 11:16:58.423 5707:5707 I/trackworktime]
removed persistent notification

[04-20 11:16:58.471 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:58.471 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:58.621 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:56.986 2272:2389 D/AutofillManagerService]
Close system dialogs

[04-20 11:16:58.652 2272:3331 I/ActivityManager]
START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/net.khertan.forrunners.1.2.2.beta.apk typ=application/vnd.android.package-archive cmp=com.android.packageinstaller/.InstallStart} from uid 10071

[04-20 11:16:58.904 2272:3335 I/ActivityManager]
START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/net.khertan.forrunners.1.2.2.beta.apk typ=application/vnd.android.package-archive flg=0x2000000 cmp=com.android.packageinstaller/.InstallStaging (has extras)} from uid 10023

[04-20 11:16:58.623 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:16:59.104 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:59.177 2272:3335 I/ActivityManager]
START u0 {act=android.intent.action.VIEW dat=file:///data/user_de/0/com.android.packageinstaller/no_backup/package3634936556649682833.apk flg=0x10000 cmp=com.android.packageinstaller/.PackageInstallerActivity (has extras)} from uid 10023

[04-20 11:16:59.104 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:59.282 31751:31751 I/AppSecurityPermissions]
Ignoring unknown permission:com.google.android.gms.permission.ACTIVITY_RECOGNITION

[04-20 11:16:59.415 2272:2391 I/ActivityManager]
Displayed com.android.packageinstaller/.PackageInstallerActivity: +190ms (total +625ms)

[04-20 11:16:59.507 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:59.507 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:59.662 2272:5457 I/OpenGLRenderer]
Initialized EGL, version 1.4

[04-20 11:16:59.662 2272:5457 D/OpenGLRenderer]
Swap behavior 2

[04-20 11:16:59.874 2272:2297 I/zygote64]
NativeAlloc concurrent copying GC freed 33481(1840KB) AllocSpace objects, 1(20KB) LOS objects, 44% free, 15MB/27MB, paused 802us total 211.964ms

[04-20 11:16:59.962 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:16:59.963 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:00.225 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:00.225 2272:12396 I/ActivityManager]
START u0 {dat=file:///data/user_de/0/com.android.packageinstaller/no_backup/package3634936556649682833.apk cmp=com.android.packageinstaller/.InstallInstalling (has extras)} from uid 10023

[04-20 11:17:00.226 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:00.522 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:00.522 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:00.667 31751:31770 D/OpenGLRenderer]
endAllActiveAnimators on 0x7293fc1800 (RippleDrawable) with handle 0x72ad3128c0

[04-20 11:17:00.712 2272:2391 I/ActivityManager]
Displayed com.android.packageinstaller/.InstallInstalling: +402ms

[04-20 11:17:00.952 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:01.340 2272:12396 I/ActivityManager]
START u0 {dat=file:///data/user_de/0/com.android.packageinstaller/no_backup/package3634936556649682833.apk flg=0x2000000 cmp=com.android.packageinstaller/.InstallFailed (has extras)} from uid 10023

[04-20 11:17:00.953 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:01.438 31751:31751 D/InstallFailed]
Installation status code: 1

[04-20 11:17:01.523 2272:2297 I/zygote64]
Background concurrent copying GC freed 29828(4MB) AllocSpace objects, 159(7MB) LOS objects, 42% free, 16MB/28MB, paused 2.503ms total 238.672ms

[04-20 11:17:01.557 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:01.557 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:01.579 2272:2391 I/ActivityManager]
Displayed com.android.packageinstaller/.InstallFailed: +146ms

[04-20 11:17:01.960 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:01.960 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:02.338 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:02.339 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:02.511 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:02.511 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:02.549 31751:31770 D/OpenGLRenderer]
endAllActiveAnimators on 0x7293f7f800 (RippleDrawable) with handle 0x729398eba0

[04-20 11:17:02.829 3080:3103 I/zygote64]
NativeAlloc concurrent copying GC freed 58134(2MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/27MB, paused 323us total 195.028ms

[04-20 11:17:02.986 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:02.986 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:03.107 2015:2122 I/ThermalEngine]
Monitor : quiet_therm = 39, msm_therm = 41, ufs_therm = 40, battery_therm = 343,current_now = 611000 

[04-20 11:17:03.396 2272:32662 I/ActivityManager]
START u0 {flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10032

[04-20 11:17:03.418 3080:3080 E/BufferItemConsumer]
[unnamed-3080-136] Failed to release buffer: Unknown error -1 (1)

[04-20 11:17:03.460 2272:2389 D/AutofillManagerService]
Close system dialogs

[04-20 11:17:03.478 3080:3080 E/BufferItemConsumer]
[unnamed-3080-137] Failed to release buffer: Unknown error -1 (1)

[04-20 11:17:03.557 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:03.558 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:03.853 3080:3103 I/zygote64]
NativeAlloc concurrent copying GC freed 13345(650KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 14MB/28MB, paused 148us total 183.245ms

[04-20 11:17:04.016 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:04.016 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:04.299 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:04.303 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:04.308 2272:2297 I/zygote64]
NativeAlloc concurrent copying GC freed 19422(1274KB) AllocSpace objects, 12(520KB) LOS objects, 43% free, 15MB/27MB, paused 551us total 351.416ms

[04-20 11:17:04.328 3080:3080 E/BufferItemConsumer]
[unnamed-3080-138] Failed to release buffer: Unknown error -1 (1)

[04-20 11:17:04.428 2272:2358 E/NotificationService]
Suppressing notification from package by user request.

[04-20 11:17:04.435 32393:32393 D/MyDeviceLogs]
[Logcat] onActivityInForeground

[04-20 11:17:04.436 32393:32393 D/MyDeviceLogs]
[Logcat] Posting pending logs

[04-20 11:17:04.440 3080:3080 E/BufferItemConsumer]
[unnamed-3080-139] Failed to release buffer: Unknown error -1 (1)

[04-20 11:17:04.445 2272:2389 D/AutofillManagerService]
Close system dialogs

[04-20 11:17:04.460 32393:32393 D/MyDeviceLogs]
[LogcatLiveFragment] onServiceConnected

[04-20 11:17:04.650 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:04.650 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:04.872 32393:32404 I/zygote64]
Background concurrent copying GC freed 94962(8MB) AllocSpace objects, 10(200KB) LOS objects, 72% free, 4MB/16MB, paused 443us total 367.124ms

[04-20 11:17:04.940 547:547 E/lowmemorykiller]
Error opening /dev/memcg/apps/uid_99095/pid_7074/memory.soft_limit_in_bytes; errno=2

[04-20 11:17:04.942 547:547 E/lowmemorykiller]
Error opening /dev/memcg/apps/uid_99071/pid_3050/memory.soft_limit_in_bytes; errno=2

[04-20 11:17:05.038 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:05.038 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1

[04-20 11:17:05.255 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:05.256 2021:10838 I/AudioPolicyManagerCustom]
FLAG None hence request for a primary output

[04-20 11:17:05.313 3080:11493 I/zygote64]
Explicit concurrent copying GC freed 25426(1163KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/27MB, paused 160us total 404.386ms

[04-20 11:17:05.454 3080:3080 W/StaticLayout]
maxLineHeight should not be -1.  maxLines:1 lineCount:1
```

**Comment by akamaus** [comment]
latest 1.2.2beta1 doesnt install
```
I/Timeline( 9182): Timeline: Activity_windows_visible id: ActivityRecord{2c8cf1d u0 com.android.packageinstaller/.InstallAppProgress t12964} time:230058970
W/PackageManager( 9182): Failed collect during installPackageLI
W/PackageManager( 9182): android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl1050761086.tmp/base.apk has no certificates at entry AndroidManifest.xml
W/PackageManager( 9182):        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1099)
W/PackageManager( 9182):        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1052)
W/PackageManager( 9182):        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:10757)
W/PackageManager( 9182):        at com.android.server.pm.PackageManagerService.access$2300(PackageManagerService.java:242)
W/PackageManager( 9182):        at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8805)
W/PackageManager( 9182):        at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager( 9182):        at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager( 9182):        at android.os.Looper.loop(Looper.java:135)
W/PackageManager( 9182):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager( 9182):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by jedie** [comment]
confirm: I also can't install 1.2.2beta1 :(

**Comment by schumar** [comment]
I can confirm the crash-on-start for 1.2.1beta,
```
E/AndroidRuntime(17243): FATAL EXCEPTION: main
E/AndroidRuntime(17243): Process: net.khertan.forrunners, PID: 17243
E/AndroidRuntime(17243): java.lang.NullPointerException: collection == null
E/AndroidRuntime(17243):        at android.os.Parcel.readException(Parcel.java:1552)
E/AndroidRuntime(17243):        at android.os.Parcel.readException(Parcel.java:1499)
E/AndroidRuntime(17243):        at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:700)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1589)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1586)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2232)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:742)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:732)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech.getVoices(TextToSpeech.java:1586)
E/AndroidRuntime(17243):        at org.apache.cordova.speech.SpeechSynthesis.getVoices(SpeechSynthesis.java:172)
E/AndroidRuntime(17243):        at org.apache.cordova.speech.SpeechSynthesis.onInit(SpeechSynthesis.java:258)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech.access$1400(TextToSpeech.java:59)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2146)
E/AndroidRuntime(17243):        at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2101)
E/AndroidRuntime(17243):        at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime(17243):        at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime(17243):        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime(17243):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17243):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(17243):        at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(17243):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17243):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17243):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(17243):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(17243):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
W/ActivityManager( 1020):   Force finishing activity 1 net.khertan.forrunners/.MainActivity
```

as well as the non-installabilty of 1.2.2beta

```
W/PackageManager( 1020): Failed collect during installPackageLI
W/PackageManager( 1020): android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl1094076157.tmp/base.apk has no certificates at entry AndroidManifest.xml
W/PackageManager( 1020):        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1096)
...
```

as well as #50 -- GPS icon does not appear at all.

Tested on 2 phones, one with Android 5.1, the other with 7.0
